name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # The tests do a lot of networking and can be unstable.
      # With a huge matrix that we have it's better to rerun failed jobs.
      fail-fast: false
      matrix:
        node-version: [6.11, 10.x, 12.x]
        cassandra-version: [3.11.4]
        test-target: [sqlite, cassandra]
        test-mode: [fs, fefs, febe]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Cassandra
      if: matrix.test-target == 'cassandra'
      uses: fabasoad/setup-cassandra-action@v1.0.1
      with:
        host: '127.0.0.1'
        connect-timeout: 30
    - run: npm install
    - run: npm run lint && npm run coverage -- ${{ matrix.test-target }} ${{ matrix.test-mode }}
      env:
        RB_CASSANDRA_HOST: '127.0.0.1'
